apiVersion: v1
kind:  Service
metadata:
  name: eks-kubeginners-service
spec:
  type: NodePort
  selector:
    app : eks-kubeginners-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 #Pods port
      nodePort: 30006

